### ISSUE TITLE
Use One Pace discord for arc images

### ISSUE THREAD

**Issue by Aaryaman-1409** [jwueller/jellyfin-plugin-onepace#1]
Hey, just wanted to say thank you for the project and all the work you've done. The only issue I'm currently facing is that most of the arcs don't have an associated image, presumably because the One Pace website doesn't have them as well. So, I was wondering if you could instead use the One Pace discord. I've seen you post about this plugin there before, so I'm presuming you still have access to the discord. The "frequently-asked-questions" channel has a zip with all of the arc images, and they are labelled quite nicely for use within your project. If the images are too large to host or include within the plugin, I wouldn't mind if you compressed them to save space. Thank you and let me know if the suggestion sounds good.

**Comment by jwueller** [comment]
I've been thinking about how to deal with this whole thing.

The problem is that there is way more than one option for alternative cover art at this point. Multiple people have made different cover art and adding support for all of them to the plugin doesn't seem great from a usability perspective.

At the same time, the One Pace team is currently working on official cover art for the project. As soon as that is released, it would probably replace the placeholder art anyway.

I'm open to ideas on how to proceed here.

**Comment by Aaryaman-1409** [comment]
Honestly yeah that make sense. No point to overcomplicate the plug-in when proper cover art will eventually be published anyway. You’re also right about the usability aspect since many different people might want different alternative sources. So yeah I’m good with closing this issue. Ultimately, it’s better for people to just manually update the arc posters. It’s slightly time consuming but it’s only a one time process and not worth the effort to optimize via the plugin.
