### ISSUE TITLE
Metadata Downloaders not showing

### ISSUE THREAD

**Issue by calgara12** [jwueller/jellyfin-plugin-onepace#50]
Hello, first of all thank you for all of your efforts.

I am having the issue that i cannot add the metadata downloaders because they are not there.
Do you have an idea why? 
The plugin is installed, however it says "Not supported". Is that the issue? I am running Version 10.8.10
![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/28657023/177aefcb-2f49-4a89-b6c7-3f2ad3412b32)

![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/28657023/6f15a571-a0ce-45be-8d94-ba5c550ee137)

![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/28657023/e9093d51-0534-4dc4-9d26-35ce55024f85)
![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/28657023/2a8e4d3f-4341-40a0-8fe3-de23ba539d6b)

Thank you so much in advance, im sure im just overlooking something obvious.

**Comment by jwueller** [comment]
Hi!

Version 1.4.0.0 bumped the minimum required version to [Jellyfin 10.8.13](https://github.com/jellyfin/jellyfin/releases/tag/v10.8.13) due to [a critical security vulnerability in Jellyfin 10.8.10](https://github.com/jellyfin/jellyfin/security/advisories/GHSA-9p5f-5x8v-x65m). You might want to upgrade your instance to a hotfixed release.

I guess I should put the version requirement somewhere in the README. :slightly_smiling_face: 

Please feel free to reopen this if you are still encountering issues with 10.8.13 or higher!
