### ISSUE TITLE
One Piece Kai

### ISSUE THREAD

**Issue by AaronMDalton** [jwueller/jellyfin-plugin-onepace#55]
So, idk if this is the right place to to do this, and if its not and come off offensive please delete/disregard. 

To my ask: One Pace is great and all but i think there are alot of people who prefer One Piece Kai (non remastered[story isnt changed], further along in their dubbing set, and other reasons)

Is there any way you can add in functionality to properly scrape for the One Piece Kai set also? I have both in my Jelly fin library and watch both often. But i would love for the Kai set to actually look retail too and there are lots of images available to do this already. 

Its much simpler and smaller of a content load. (ie few # of seasons/episodes)

![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/80536982/d01d3506-f16b-4de2-afcc-025ea1d9100c)

If not please delete and disregard. If so please tell me how i can go about buying you a coffee or something. ;)

**Comment by Camotoy** [comment]
Seeing as jwueller is on the One Pace team (most likely) and TheShrubberyDemander has taken down his edits, I don't think you're going to get very far in this request. Also, this plugin plugs into One Pace's API, and that provides the titles, description, and thumbnails. One Piece Kai does not have an API, so you'd have to create brand-new data for a discontinued edit.

As an alternative, Discord user Muhny has made their own unofficial take on One Piece edits, which appear to follow One Pace's format and might be able to be plugged right into this plugin (and will also likely get edits further into Wano, but that won't get metadata from One Pace). You can find those here: https://discord.com/channels/229653982530764800/1093723457344254053/1186112637986144256 

Best of luck!

**Comment by jwueller** [comment]
No offense taken, but @Camotoy is right. There doesn't really seem to be much overlap between the two projects, from what I understand. You might have noticed that this repository doesn't actually contain any of the images or data. That's because all of it comes straight from the One Pace API, which obviously doesn't track any third-party edits.

That said, the code is open source, and if someone wants to reuse the file matching portion to work for other edits and maintain the data for them, they are welcome to fork this repository. I have no idea how useful my code will be though, since I don't know what filename patterns for other edits look like, or whether they even follow a consistent pattern at all.
