### ISSUE TITLE
Jellyfin 10.9 support

### ISSUE THREAD

**Issue by Camotoy** [jwueller/jellyfin-plugin-onepace#57]
Hello! It would appear the current version of this plugin does not support the new Jellyfin 10.9 update. Thanks!

**Comment by jwueller** [comment]
I'll take a look! Thanks for letting me know.

**Comment by jwueller** [comment]
Jellyfin 10.9 caused some breaking changes, which I had to fix. I just released v1.5.1.0, seems to run well on my personal instance. Please give it a go!

**Comment by Camotoy** [comment]
Thanks for taking care of this so quickly! A couple of things I noticed:
- I had to re-enable the One Pace metadata downloader in my library, but that's likely because of updating a disabled plugin.
- Season numbers were bumped up, but I assume that's because of Adventures of the Straw Hats. Fixed by a complete metadata redownload.
- Season names were gone, but that was also fixed by a complete metadata redownload.

**Comment by jwueller** [comment]
Yes, I think the plugin as well as the downloader sometimes get disabled if they run into issues, but I don't really understand what exactly triggers it. Sometimes it also just works. :shrug:

And yes, things got shuffled around a bit on the Pace side, so it probably had a weird in-between state cached. The problem is that Jellyfin doesn't always catch all of the updates, because it primarily looks at the files changing, not the data. So sometimes you unfortunately need to do an explicit refresh, discarding old data.

Glad to hear it works now!
