### ISSUE TITLE
One Pace10.9.6.13 Status NotSupported

### ISSUE THREAD

**Issue by tsefcsst3** [jwueller/jellyfin-plugin-onepace#69]
Server name
Home
Server version
10.9.2
Web version
10.9.2
Build version
10.9.2
![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/132886109/a1022896-3620-42db-a1fe-238845d6e3e0)

**Comment by jwueller** [comment]
Jellyfin has received several security patches that required raising the minimum required version. It's heavily recommended that you upgrade to the latest version! I'll see to get the plugin up-to-date with whichever version is current soon.

Unfortunately, since the One Pace website is currently down, the plugin can't do any real work at the moment. Track #66 for nicer fallback behavior.
